### ISSUE TITLE
Error running gubbins_drawer.py with v. 2.2.0

### ISSUE THREAD

**Issue by robynslee** [nickjcroucher/gubbins#184]
Hi there,

I hope you can help? I keep getting the error "AttributeError: 'SeqFeature' object has no attribute 'sub_features'" when attempting to run gubbins_drawer.py. 

The command used was:
gubbins_drawer.py -o test_gub.pdf -t core.full.final_tree.tre core.full.branch_base_reconstruction.embl

Full output:
28360 features found for core.full.branch_base_reconstruction.embl
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 685, in <module>
    new_tracks=add_ordered_tab_to_diagram(arg)
  File "/home/linuxbrew/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 250, in add_ordered_tab_to_diagram
    new_tracks=add_ordered_embl_to_diagram(record, incfeatures=["i", "d", "li", "del", "snp", "misc_feature", "core", "cds", "insertion", "deletion", "recombination", "feature", "blastn_hit", "fasta_record", "variation"], emblfile=False)
  File "/home/linuxbrew/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 204, in add_ordered_embl_to_diagram
    locations=iterate_subfeatures(feature, locations)
  File "/home/linuxbrew/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 142, in iterate_subfeatures
    if len(feature.sub_features)>0:
AttributeError: 'SeqFeature' object has no attribute 'sub_features'

I wonder if it might be related to this: https://github.com/chapmanb/bcbb/issues/110

Thanks.
Best,
Robyn

**Comment by seifst** [comment]
I am running into the same issue on Ubuntu 14.04 and Mac OSX Yosemite whether I use Biopython 1.68, 1.67, or 1.66.  Any work around would be greatly appreciated! 

Full output:
 gubbins_drawer.py -o filename.pdf ~/Desktop/Gubbins/filename.final_tree.tre ~/Desktop/Gubbins/filename.recombination_predictions.embl 
43 features found for /home/steph/Desktop/Gubbins/filename.recombination_predictions.embl
Traceback (most recent call last):
  File "/home/steph/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 685, in <module>
    new_tracks=add_ordered_tab_to_diagram(arg)
  File "/home/steph/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 250, in add_ordered_tab_to_diagram
    new_tracks=add_ordered_embl_to_diagram(record, incfeatures=["i", "d", "li", "del", "snp", "misc_feature", "core", "cds", "insertion", "deletion", "recombination", "feature", "blastn_hit", "fasta_record", "variation"], emblfile=False)
  File "/home/steph/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 204, in add_ordered_embl_to_diagram
    locations=iterate_subfeatures(feature, locations)
  File "/home/steph/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/gubbins_drawer.py", line 142, in iterate_subfeatures
    if len(feature.sub_features)>0:
AttributeError: 'SeqFeature' object has no attribute 'sub_features'

**Comment by ammaraziz** [comment]
An input file would help with debugging. Also potentially running verbose mode will also give a better idea of the issue.

**Comment by bogemad** [comment]
For anyone still having this problem, I've managed to solve this by using biopython <= 1.65. I believe that .sub_features are now depreciated in biopython.

**Comment by andrewjpage** [comment]
Fixed
