### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by sekhwal** [nickjcroucher/gubbins#332]
hi, I am getting following error when I run the Gubbins.
$ generate_ska_alignment.py --reference NC_336.1.fasta --fasta PMEN3_isolates.list --out out.aln

Error------------

Traceback (most recent call last):
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 579, in _build_master
    ws.require(__requires__)
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 788, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (gubbins 3.1.6 (/home/anaconda3/envs/gubbins/lib/python3.9/site-packages), Requirement.parse('gubbins==3.1.4'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/gubbins/bin/generate_ska_alignment.py", line 4, in <module>
    __import__('pkg_resources').run_script('gubbins==3.1.4', 'generate_ska_alignment.py')
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3247, in <module>
    def _initialize_master_working_set():
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3221, in _call_aside
    f(*args, **kwargs)
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3259, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 594, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/anaconda3/envs/gubbins/lib/python3.9/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gubbins==3.1.4' distribution was not found and is required by the application

**Comment by nickjcroucher** [comment]
The script can't find the installed gubbins package. It would be worth trying the latest version (3.1.6) in a clean conda environment - I think there were some teething problems with these scripts finding the package.

**Comment by sekhwal** [comment]
I created new conda environment and installed Gubbins. However, once I run the program, it shows the same error. Please let me know where I can find the new version of this script.

**Comment by nickjcroucher** [comment]
@jdaeth274 has identified the likely problem - something odd happened to the script code when ensuring it installed properly, you can get the original from https://raw.githubusercontent.com/nickjcroucher/gubbins/c9bdb6b83fb9e75b1e34e2c32da22e46d0296364/python/scripts/generate_ska_alignment.py.
