### ISSUE TITLE
problem of installing gubbins from the repository

### ISSUE THREAD

**Issue by liuqian666** [nickjcroucher/gubbins#335]
Hello! I want to install **gubbins version 3.2** from github, and use the command **mask_gubbins_aln.py**
so I follow the steps from this:

conda create -c bioconda -n gubbins_git gubbins python=3.9
conda activate gubbins_git
conda install -c conda-forge libtool autoconf-archive automake pkg-config check pytest
conda remove --force gubbins
git clone https://github.com/nickjcroucher/gubbins
cd gubbins
autoreconf -i
chmod +x configure 
./configure --prefix=$CONDA_PREFIX
make
sudo make install
cd python

All the above commands goes well. However, when I run this command **python setup.py install**, it showed that：

running install
/home/epi-linux/anaconda3/envs/gubbins_git/lib/python3.9/site-packages/setuptools/command/install.py:34:SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.  warnings.warn(
/home/epi-linux/anaconda3/envs/gubbins_git/lib/python3.9/site-packages/setuptools/command/easy_install.py:144:EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.  warnings.warn(
running bdist_egg
running egg_info
error: [Errno 13] Permission denied

How to solve this problem? Or is there any other way to install mask_gubbins_aln.py?
Look forward to your reply. Thank you very much.

**Comment by nickjcroucher** [comment]
There's been a change to the method of installing the python aspect, can you try:
`sudo python -m pip install .` (if you have admin rights)
else
`python -m pip install --target=$CONDA_PREFIX .` (otherwise)

**Comment by liuqian666** [comment]
> 

Thank you for your quick reply. I've tried two way, it's still failed. 
**command one：**
`sudo python -m pip install .`

**it shows：**
```
The directory '/home/epi-linux/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabl
ed. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.The directory '/home/epi-linux/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabl
ed. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /media/epi-linux/8t/2_liuqian/software/gubbins/python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zaVwDB/setup.py", line 7, in <module>
        version = open('VERSION').read().strip(),
    IOError: [Errno 2] No such file or directory: 'VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-zaVwDB/
You are using pip version 18.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Then I tried to upgrade pip, it shows:**
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in /home/epi-linux/anaconda3/envs/gubbins_git/lib/python3.9/site-packages (22.0.4)
```

**Command two:**
`python -m pip install --target=$CONDA_PREFIX .`

**It shows:**
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /media/epi-linux/8t/2_liuqian/software/gubbins/python
  Preparing metadata (setup.py) ... done
Collecting biopython>=1.59
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/10/4f/1369f4a2840fdd37402935a59455f0c86a5abfcfdfae37365d8be925661c/biopython-
1.79-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 1.6 MB/s eta 0:00:00
Collecting dendropy>=4.0.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f9/10/125c181b1d97ffc4661a60ec897cfe058dc46cb53900d807819464c3510f/DendroPy-
4.5.2.tar.gz (15.2 MB)  Preparing metadata (setup.py) ... done
Collecting multiprocess>=0.70
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e3/12/c1c7b5574a574a5bc898c8656b0ab8514d0609356b3ca18180e2ae94c2f7/multiproce
ss-0.70.12.2-py39-none-any.whl (128 kB)     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.7/128.7 KB 1.5 MB/s eta 0:00:00
Collecting scipy>=1.5.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b8/51/6a058c1c742c8365399c93685a5b3c4f9c39389957189725738954c427a0/scipy-1.8.
0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.1 MB)     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 1.4 MB/s eta 0:00:00
Collecting numpy>=1.19
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/25/2f/811ad95effd790cd13cdea494e1cd7520ebc3bf049c3e88c3ca4ba8175c5/numpy-1.22
.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 1.8 MB/s eta 0:00:00
Collecting setuptools
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7c/5b/3d92b9f0f7ca1645cba48c080b54fe7d8b1033a4e5720091d1631c4266db/setuptool
s-60.10.0-py3-none-any.whl (1.1 MB)Collecting dill>=0.3.4
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4
-py2.py3-none-any.whl (86 kB)     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.9/86.9 KB 1.3 MB/s eta 0:00:00
Building wheels for collected packages: gubbins, dendropy
  Building wheel for gubbins (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_scripts
      copying and adjusting scripts/generate_ska_alignment.py -> build/scripts-3.9
      copying and adjusting scripts/extract_gubbins_clade.py -> build/scripts-3.9
      copying and adjusting scripts/mask_gubbins_aln.py -> build/scripts-3.9
      copying and adjusting scripts/gubbins_alignment_checker.py -> build/scripts-3.9
      /home/epi-linux/anaconda3/envs/gubbins_git/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWa
rning: setup.py install is deprecated. Use build and pip and other standards-based tools.        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64/wheel
      error: could not create 'build/bdist.linux-x86_64/wheel': Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gubbins
  Running setup.py clean for gubbins
  Building wheel for dendropy (setup.py) ... done
  Created wheel for dendropy: filename=DendroPy-4.5.2-py3-none-any.whl size=452941 sha256=bc70d7c3d6f2f0e47d0a568fa8276097b077dd601ea3
10aefe584ea37aa9232c  Stored in directory: /home/epi-linux/.cache/pip/wheels/c5/04/ed/ed990a85aed948dafd074bce6f489a8027c449447d2fad8ee5
Successfully built dendropy
Failed to build gubbins
Installing collected packages: setuptools, numpy, dill, scipy, multiprocess, dendropy, biopython, gubbins
  Running setup.py install for gubbins ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for gubbins did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      running install
      /home/epi-linux/anaconda3/envs/gubbins_git/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWa
rning: setup.py install is deprecated. Use build and pip and other standards-based tools.        warnings.warn(
      running build
      running build_py
      creating build/lib
      creating build/lib/gubbins
      copying gubbins/utils.py -> build/lib/gubbins
      copying gubbins/treebuilders.py -> build/lib/gubbins
      copying gubbins/common.py -> build/lib/gubbins
      copying gubbins/pyjar.py -> build/lib/gubbins
      copying gubbins/ValidateFastaAlignment.py -> build/lib/gubbins
      copying gubbins/__init__.py -> build/lib/gubbins
      copying gubbins/run_gubbins.py -> build/lib/gubbins
      copying gubbins/PreProcessFasta.py -> build/lib/gubbins
      creating build/lib/gubbins/tests
      copying gubbins/tests/test_pre_process_fasta.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_treebuilders.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_tree_methods.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_validate_fasta_input.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_alignment_python_methods.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_utils.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_validate_starting_tree.py -> build/lib/gubbins/tests
      copying gubbins/tests/__init__.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_python_scripts.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_converging_recombinations.py -> build/lib/gubbins/tests
      copying gubbins/tests/test_dependencies.py -> build/lib/gubbins/tests
      running build_scripts
      creating build/scripts-3.9
      copying and adjusting scripts/generate_ska_alignment.py -> build/scripts-3.9
      copying and adjusting scripts/extract_gubbins_clade.py -> build/scripts-3.9
      copying and adjusting scripts/mask_gubbins_aln.py -> build/scripts-3.9
      copying and adjusting scripts/gubbins_alignment_checker.py -> build/scripts-3.9
      changing mode of build/scripts-3.9/generate_ska_alignment.py from 664 to 775
      changing mode of build/scripts-3.9/extract_gubbins_clade.py from 664 to 775
      changing mode of build/scripts-3.9/mask_gubbins_aln.py from 664 to 775
      changing mode of build/scripts-3.9/gubbins_alignment_checker.py from 664 to 775
      running install_lib
      creating /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/utils.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/treebuilders.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      creating /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_pre_process_fasta.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_treebuilders.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_tree_methods.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_validate_fasta_input.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_alignment_python_methods.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_utils.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_validate_starting_tree.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/__init__.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_python_scripts.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_converging_recombinations.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/tests/test_dependencies.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests
      copying build/lib/gubbins/common.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/pyjar.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/ValidateFastaAlignment.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/__init__.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/run_gubbins.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      copying build/lib/gubbins/PreProcessFasta.py -> /tmp/pip-target-2pb3pa_z/lib/python/gubbins
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/utils.py to utils.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/treebuilders.py to treebuilders.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_pre_process_fasta.py to test_pre_process_fasta.cpython-39.
pyc      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_treebuilders.py to test_treebuilders.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_tree_methods.py to test_tree_methods.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_validate_fasta_input.py to test_validate_fasta_input.cpyth
on-39.pyc      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_alignment_python_methods.py to test_alignment_python_metho
ds.cpython-39.pyc      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_utils.py to test_utils.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_validate_starting_tree.py to test_validate_starting_tree.c
python-39.pyc      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/__init__.py to __init__.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_python_scripts.py to test_python_scripts.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_converging_recombinations.py to test_converging_recombinat
ions.cpython-39.pyc      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/tests/test_dependencies.py to test_dependencies.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/common.py to common.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/pyjar.py to pyjar.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/ValidateFastaAlignment.py to ValidateFastaAlignment.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/__init__.py to __init__.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/run_gubbins.py to run_gubbins.cpython-39.pyc
      byte-compiling /tmp/pip-target-2pb3pa_z/lib/python/gubbins/PreProcessFasta.py to PreProcessFasta.cpython-39.pyc
      running install_egg_info
      running egg_info
      error: [Errno 13] Permission denied
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gubbins

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by nickjcroucher** [comment]
There's a problem with your file permissions, indicated by:
`error: could not create 'build/bdist.linux-x86_64/wheel': Permission denied`
You'll need to contact your local sysadmin team I'm afraid.

**Comment by liuqian666** [comment]
> There's a problem with your file permissions, indicated by: `error: could not create 'build/bdist.linux-x86_64/wheel': Permission denied` You'll need to contact your local sysadmin team I'm afraid.

Ok, Thank you very much~
