### ISSUE TITLE
I use run_gubbins.py -P to test and get an error, but I don't know how to solve it, please help

### ISSUE THREAD

**Issue by xianglongwei** [nickjcroucher/gubbins#346]
raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function contains>) found for signature:
 
 >>> contains(array(int32, 1d, A), int32)
 
There are 18 candidate implementations:
  - Of which 18 did not match due to:
  Overload of function 'contains': File: <numerous>: Line N/A.
    With argument(s): '(array(int32, 1d, A), int32)':
   No match.

During: typing of intrinsic-call at /NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/gubbins/pyjar.py (312)

File "../../../../../miniconda3/lib/python3.8/site-packages/gubbins/pyjar.py", line 312:
def reconstruct_alleles(reconstructed_alleles,
    <source elided>
    for node_index in postordered_nodes:
        if node_index in leaf_nodes:
        ^

---------------------------------------------------------------------------------------
Environment centos linux 64, use conda to install gubbins_3.2.1
![image](https://user-images.githubusercontent.com/52027227/185345380-b68ae65c-caa6-4bd0-b0c0-3bee405f48ba.png)

**Comment by xianglongwei** [comment]
Traceback (most recent call last):
  File "/NAS/home/chenyx/miniconda3/bin/run_gubbins.py", line 33, in <module>
    sys.exit(load_entry_point('gubbins==3.1.4', 'console_scripts', 'run_gubbins.py')())
  File "/NAS/home/chenyx/miniconda3/bin/run_gubbins.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/gubbins/__init__.py", line 16, in <module>
    from gubbins import common
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/gubbins/common.py", line 43, in <module>
    from gubbins.pyjar import jar, read_alignment, get_base_patterns
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/gubbins/pyjar.py", line 326, in <module>
    def reconstruct_alleles(reconstructed_alleles,
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/decorators.py", line 218, in wrapper
    disp.compile(sig)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 819, in compile
    cres = self._compiler.compile(args, return_type)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 82, in compile
    raise retval
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 92, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 105, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 625, in compile_extra
    return pipeline.compile_extra(func)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 361, in compile_extra
    return self._compile_bytecode()
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 423, in _compile_bytecode
    return self._compile_core()
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 403, in _compile_core
    raise e
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler.py", line 394, in _compile_core
    pm.run(self.state)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/typed_passes.py", line 92, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/typed_passes.py", line 70, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/numba/core/typeinfer.py", line 1071, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function contains>) found for signature:
 
 >>> contains(array(int32, 1d, A), int32)
 
There are 18 candidate implementations:
  - Of which 18 did not match due to:
  Overload of function 'contains': File: <numerous>: Line N/A.
    With argument(s): '(array(int32, 1d, A), int32)':
   No match.

During: typing of intrinsic-call at /NAS/home/chenyx/miniconda3/lib/python3.8/site-packages/gubbins/pyjar.py (334)

File "../../../../../miniconda3/lib/python3.8/site-packages/gubbins/pyjar.py", line 334:
def reconstruct_alleles(reconstructed_alleles,
    <source elided>
    for node_index in postordered_nodes:
        if node_index in leaf_nodes:
---------------------------------------------------------------------------
I lowered the version, same error

**Comment by nickjcroucher** [comment]
Does this still happen if you upgrade to v3.2.1?
________________________________

**Comment by xianglongwei** [comment]
Yes 3.2.1, I currently use the gubbins-3.1.4-py38h390ddb8_0.tar.bz2 version and it runs normally, and the versions after gubbins-3.1.4-py38h390ddb8_0.tar.bz2 have the same problem

**Comment by nickjcroucher** [comment]
It looks as though some of version 3.1.4 is still lingering can you try a clean install in a new conda env?
________________________________

**Comment by xianglongwei** [comment]
I'm very sorry, the installation operation cannot be performed at the moment. It took me 2 days to install it and it can be used. If it is solved in the future, please let me know. thanks

**Comment by nickjcroucher** [comment]
OK - beware that the error includes the line:
`sys.exit(load_entry_point('gubbins==3.1.4', 'console_scripts', 'run_gubbins.py')())`
indicating version 3.1.4 is still being used for some aspects of the analysis - this is likely not compatible with the 3.2.1 installation. I suspect the error reflects this mismatch in installed packages rather than a bug with the current release.
