### ISSUE TITLE
Numba issues

### ISSUE THREAD

**Issue by leabednarczuk** [nickjcroucher/gubbins#364]
Hello

I installed Github with conda as explained in the documentation. Then I created my alignment with SKA and I obtained my .aln output. The issues occur when I try to run this line : $ run_gubbins.py test.aln

Here what the terminal display:

Traceback (most recent call last):
  File "/home/bednarczuk/anaconda3/bin/run_gubbins.py", line 33, in <module>
    sys.exit(load_entry_point('gubbins==3.2.1', 'console_scripts', 'run_gubbins.py')())
  File "/home/bednarczuk/anaconda3/bin/run_gubbins.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/bednarczuk/anaconda3/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/bednarczuk/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bednarczuk/anaconda3/lib/python3.10/site-packages/gubbins/__init__.py", line 16, in <module>
    from gubbins import common
  File "/home/bednarczuk/anaconda3/lib/python3.10/site-packages/gubbins/common.py", line 42, in <module>
    from gubbins.pyjar import jar, get_base_patterns
  File "/home/bednarczuk/anaconda3/lib/python3.10/site-packages/gubbins/pyjar.py", line 18, in <module>
    import numba
  File "/home/bednarczuk/anaconda3/lib/python3.10/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/bednarczuk/anaconda3/lib/python3.10/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/bednarczuk/anaconda3/lib/python3.10/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

It looks like the problem is the Numba package so I tried to re install it but I still get this error message. 

Thank you in advance for your precious help !

**Comment by nickjcroucher** [comment]
It seems this might be a problem with the latest version of numpy interfacing with numba: https://github.com/numba/numba/issues/8615#issuecomment-1434358853.

Would you mind trying downgrading numpy to 1.23.0, as suggested in that link, in case that fixes the problem?

**Comment by leabednarczuk** [comment]
It worked thank you very much !

**Comment by nickjcroucher** [comment]
Pinned `numpy` version in [3cfec5c](https://github.com/nickjcroucher/gubbins/commit/3cfec5c6137af69dc7eeef6aa79118ee7c9bf524).
