### ISSUE TITLE
from numpy.core._multiarray_umath import ( KeyboardInterrupt

### ISSUE THREAD

**Issue by qianxin-kxy** [nickjcroucher/gubbins#371]
### Hello, I ran Gubbins through the following code and encountered the following error. I don't know where the problem occurred?

**$  run_gubbins.py -p gubbins clean.full.aln --threads 100**

Running joint ancestral reconstruction with pyjar
OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 22 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
………………There are many similar codes………………
OpenBLAS blas_thread_init: pthread_create failed for thread 125 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: pthread_create failed for thread 126 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 126 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: pthread_create failed for thread 127 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
OpenBLAS blas_thread_init: pthread_create failed for thread 127 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 4124035 max
Process SpawnPoolWorker-17:
Process SpawnPoolWorker-12:
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/gubbins/__init__.py", line 16, in <module>
    from gubbins import common
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/gubbins/common.py", line 32, in <module>
    from Bio import AlignIO
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/Bio/AlignIO/__init__.py", line 140, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/Bio/Align/__init__.py", line 25, in <module>
    import numpy
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/data/users/kxy/miniconda3/envs/gubbins/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt

### In addition, the output folder contains the following files:

clean.full.aln                                                     RAxML_log.clean.full.iteration_1
clean.full.iteration_1.tre.rooted                                  RAxML_log.clean.full.iteration_1_reconstruction
RAxML_bestTree.clean.full.iteration_1                              RAxML_parsimonyTree.clean.full.iteration_1
RAxML_binaryModelParameters.clean.full.iteration_1_reconstruction  RAxML_result.clean.full.iteration_1
RAxML_info.clean.full.iteration_1                                  RAxML_result.clean.full.iteration_1_reconstruction
RAxML_info.clean.full.iteration_1_reconstruction

**Comment by nickjcroucher** [comment]
This is not a Gubbins issue, this relates to the machine you are using: https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable. You probably need to use fewer threads.
