### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by CSouque** [nickjcroucher/gubbins#372]
Hi!

While running gubbins I am running into this RecursionError towards the end of iteration 3 (iteration 1 and 2 went well). It failed the first time and failed again once I tried re-starting from iteration 2 with --resume.

I am using gubbins version 3.3.0

```
Traceback (most recent call last):
  File "/home/cs477/mambaforge/envs/gubbins/bin/run_gubbins.py", line 33, in <module>
    sys.exit(load_entry_point('gubbins==3.3.0', 'console_scripts', 'run_gubbins.py')())
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/site-packages/gubbins/run_gubbins.py", line 164, in main
    gubbins.common.parse_and_run(parser.parse_args(), parser.description)
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/site-packages/gubbins/common.py", line 371, in parse_and_run
    jar(sequence_names = ordered_sequence_names, # complete polymorphism alignment
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/site-packages/gubbins/pyjar.py", line 825, in jar
    reconstruction_results = pool.starmap(partial(
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RecursionError: maximum recursion depth exceeded while pickling an object
```

**Comment by nickjcroucher** [comment]
What command are you using?

________________________________
From: CSouque ***@***.***>
Sent: Friday, June 9, 2023 5:14:00 AM
To: nickjcroucher/gubbins ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nickjcroucher/gubbins] RecursionError (Issue #372)


Hi!

While running gubbins I am running into this RecursionError towards the end of iteration 3 (iteration 1 and 2 went well). It failed the first time and failed again once I tried re-starting from iteration 2 with --resume.

I am using gubbins version 3.3.0

Traceback (most recent call last):
  File "/home/cs477/mambaforge/envs/gubbins/bin/run_gubbins.py", line 33, in <module>
    sys.exit(load_entry_point('gubbins==3.3.0', 'console_scripts', 'run_gubbins.py')())
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/site-packages/gubbins/run_gubbins.py", line 164, in main
    gubbins.common.parse_and_run(parser.parse_args(), parser.description)
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/site-packages/gubbins/common.py", line 371, in parse_and_run
    jar(sequence_names = ordered_sequence_names, # complete polymorphism alignment
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/site-packages/gubbins/pyjar.py", line 825, in jar
    reconstruction_results = pool.starmap(partial(
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/cs477/mambaforge/envs/gubbins/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RecursionError: maximum recursion depth exceeded while pickling an object

**Comment by CSouque** [comment]
I am using `run_gubbins.py --threads 6 -p gubbins clean.full.aln --verbose`. I am running it on a cluster and the job is set up with 36GB of memory, and I am using Python 3.9.16

**Comment by nickjcroucher** [comment]
Does it work with the --mar flag?

________________________________

**Comment by CSouque** [comment]
No, I got the same error message

**Comment by nickjcroucher** [comment]
Odd - it should not reach that part of the code with the `--mar` flag. What was your command and error message with that flag?
