### ISSUE TITLE
'Palindrome middle base not W/S: 78' in generate_ska_alignment.py

### ISSUE THREAD

**Issue by jvfe** [nickjcroucher/gubbins#378]
Hi,

I've downloaded Gubbins into a conda environment and I've tried to run it with some different datasets, but all of them result in the same issue when trying to run `generate_ska_alignment.py`:

```
SKA: Split K-mer Analysis (the alignment-free aligner)
████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2/12thread 'main' panicked at 'Palindrome middle base not W/S: 78', src/ska_dict.rs:87:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/jvfe/miniconda3/envs/recombination/bin/generate_ska_alignment.py", line 97, in <module>
    subprocess.check_output('ska build -o ' + args.out + ' -k ' + str(args.k) + \
  File "/home/jvfe/miniconda3/envs/recombination/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/jvfe/miniconda3/envs/recombination/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ska build -o out.aln -k 17 -f gubbins_samplesheet.txt --threads 1' returned non-zero exit status 101.
```

Is this something related to the input dataset or something else?
The input data consists of open assemblies (.fna) assembled through Unicycler.

Gubbins v3.3.0

**Comment by nickjcroucher** [comment]
This is an error with the new [ska2](https://github.com/bacpop/ska.rust) software - I would test whether the `ska build -o out.aln -k 17 -f gubbins_samplesheet.txt --threads 1` command works when run locally, and if not, raise it with the developers at the ska2 repo.
